"""One-shot builder for notebooks/granularity_calibration.ipynb (deleted after use)."""
import nbformat as nbf
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell

cells = []

# 1. md -- purpose
cells.append(new_markdown_cell(
    "# Granularity Calibration — adaptive headroom + training-free density→size map\n"
    "\n"
    "**H1 confirmed** (the prior sweep showed the optimal QASPER leaf size is "
    "document-dependent, spanning 50–400 tokens). Here we:\n"
    "\n"
    "- **(a)** quantify the **adaptive headroom** an oracle sizing policy has over the "
    "single best fixed leaf size,\n"
    "- **(b)** calibrate a **training-free density→size map** and evaluate it on a "
    "**held-out** split of documents,\n"
    "- **(c)** contrast that parsimonious 2-parameter map with a **learned** "
    "multi-feature regressor.\n"
    "\n"
    "**SBERT is used only for the sweep** (to measure evidence coverage); there is "
    "**no LLM** anywhere in this notebook. The density score is deterministic and "
    "training-free, and the analytical functions in `experiments.granularity_calibration` "
    "are pure stdlib (unit-tested offline)."
))

# 2. code -- clone / install / Drive / OUT
cells.append(new_code_cell(
    "!git clone -b ckraptor https://github.com/MissLostCodes/raptor.git\n"
    "%cd raptor\n"
    "!pip install -q -r requirements-colab.txt"
))
cells.append(new_code_cell(
    "# Persist the sweep output to Drive so a disconnect never loses progress; rerun resumes.\n"
    "try:\n"
    "    from google.colab import drive\n"
    "    drive.mount('/content/drive')\n"
    "    RUN_DIR = '/content/drive/MyDrive/raptor_runs'\n"
    "except Exception as e:\n"
    "    print('Not on Colab / Drive unavailable -> using local ./raptor_runs', e)\n"
    "    RUN_DIR = 'raptor_runs'\n"
    "\n"
    "import os\n"
    "os.makedirs(RUN_DIR, exist_ok=True)\n"
    "# Reuse the SAME sweep cache the GO/NO-GO notebook writes; '_50' marks the 50-doc run.\n"
    "OUT = os.path.join(RUN_DIR, 'granularity_sweep_50.json')\n"
    "print('RUN_DIR =', RUN_DIR)\n"
    "print('OUT     =', OUT)"
))

# 3. code -- load docs
cells.append(new_code_cell(
    "from experiments.datasets import get_loader\n"
    "\n"
    "docs = get_loader('qasper').load(limit=50)\n"
    "n_ans = sum(1 for d in docs for q in d.questions if q.evidence)\n"
    "print(f'{len(docs)} QASPER papers, {n_ans} answerable (gold-evidence) questions total')"
))

# 4. code -- run sweep (resumable)
cells.append(new_code_cell(
    "from experiments import granularity_sweep as gs, granularity_calibration as gc\n"
    "\n"
    "SIZES = [50, 100, 150, 200, 300, 400]   # leaf token sizes to sweep\n"
    "# SBERT-only, NO LLM. Resumable from OUT: first run can take a while (embeds every\n"
    "# chunk of every paper at every size); reruns are fast (cached records are skipped).\n"
    "records = gs.run_sweep(docs, SIZES, budget=2000, out_path=OUT)\n"
    "print(f'{len(records)} (doc, size) records')\n"
    "records[:3]"
))

# 5. code -- HEADROOM + Fig 1
cells.append(new_code_cell(
    "import matplotlib.pyplot as plt\n"
    "\n"
    "# Fig.1 + the headroom number: how much an adaptive policy could gain over the\n"
    "# single best fixed leaf size.\n"
    "h = gc.headroom(records)\n"
    "print('HEADROOM:', h)\n"
    "print(\n"
    "    f\"best fixed size = {h['best_fixed_size']} tok @ cov {h['best_fixed_cov']:.4f} | \"\n"
    "    f\"oracle cov {h['oracle_cov']:.4f} | abs_gap {h['abs_gap']:.4f} \"\n"
    "    f\"(+{h['rel_gain_pct']:.1f}% rel.)\"\n"
    ")\n"
    "\n"
    "# Mean coverage vs fixed leaf size, with the per-doc oracle as a horizontal ceiling.\n"
    "sizes_sorted = sorted({r['size'] for r in records if r['mean_evidence_coverage'] is not None})\n"
    "fixed_curve = [gc.mean_coverage_at_size(records, s) for s in sizes_sorted]\n"
    "\n"
    "plt.figure(figsize=(7, 4))\n"
    "plt.plot(sizes_sorted, fixed_curve, marker='o', label='mean coverage @ fixed size')\n"
    "plt.axhline(h['oracle_cov'], color='C3', ls='--',\n"
    "            label=f\"per-doc oracle = {h['oracle_cov']:.3f}\")\n"
    "plt.scatter([h['best_fixed_size']], [h['best_fixed_cov']], color='C1', zorder=5,\n"
    "            label=f\"best fixed = {h['best_fixed_size']} tok\")\n"
    "plt.xlabel('leaf chunk size (tokens)')\n"
    "plt.ylabel('mean evidence coverage')\n"
    "plt.title('Fig.1 — adaptive headroom: best fixed size vs per-doc oracle')\n"
    "plt.grid(True, alpha=0.3)\n"
    "plt.legend(fontsize=8)\n"
    "plt.show()"
))

# 6. code -- density features per doc + optimal sizes
cells.append(new_code_cell(
    "from raptor.chunking.density_score import density_score\n"
    "\n"
    "# Deterministic, training-free density signal per document (rho + its 6 features).\n"
    "feats = {d.doc_id: density_score(d.text)[1] for d in docs}\n"
    "rho = {d.doc_id: density_score(d.text)[0] for d in docs}\n"
    "\n"
    "# Per-doc optimal leaf size from the sweep (the calibration target).\n"
    "opt = gs.best_size_per_doc(records)\n"
    "print(f'{len(opt)} docs with a defined optimal size')\n"
    "from collections import Counter\n"
    "print('distribution of optimal sizes:', dict(Counter(opt.values())))"
))

# 7. code -- CORRELATION of rho + each feature vs optimal size
cells.append(new_code_cell(
    "# Which density signal predicts granularity? Spearman rank-corr of rho and each of\n"
    "# the 6 density features against the per-doc optimal leaf size (feature ablation).\n"
    "doc_ids = [k for k in opt if k in rho]   # docs with both a target and a score\n"
    "\n"
    "FEATURE_NAMES = [\n"
    "    'mean_sentence_len_tokens_norm',\n"
    "    'type_token_ratio',\n"
    "    'numeral_symbol_density',\n"
    "    'mean_word_len_chars_norm',\n"
    "    'list_marker_density',\n"
    "    'nonstopword_ratio',\n"
    "]\n"
    "\n"
    "opt_vec = [opt[k] for k in doc_ids]\n"
    "print(f\"{'signal':<32}{'spearman vs opt size':>22}\")\n"
    "print('-' * 54)\n"
    "rc_rho = gc.rank_corr([rho[k] for k in doc_ids], opt_vec)\n"
    "print(f\"{'rho (combined density)':<32}{rc_rho:>22.3f}\")\n"
    "for f in FEATURE_NAMES:\n"
    "    rc = gc.rank_corr([feats[k][f] for k in doc_ids], opt_vec)\n"
    "    print(f'{f:<32}{rc:>22.3f}')"
))

# 8. code -- CALIBRATE on train, EVALUATE on held-out test (Table 1)
cells.append(new_code_cell(
    "# Paper Table 1: held-out evaluation of the training-free density->size map.\n"
    "# Two training-free variants are compared:\n"
    "#   (i)  composite rho  -> size   (the equal-weight density score)\n"
    "#   (ii) BEST single feature -> size, the feature selected by |Spearman| on TRAIN\n"
    "# The pilot showed the equal-weight composite CANCELS signal (features correlate\n"
    "# with optimal size in opposite directions), so the selected-feature map is the\n"
    "# real training-free arm; rho is kept only to show the cancellation explicitly.\n"
    "tr, te = gc.train_test_split_docs(list(opt))\n"
    "print(f'{len(tr)} train docs, {len(te)} test docs')\n"
    "\n"
    "# (i) parsimonious size = a + b*rho on TRAIN only.\n"
    "fit_rho = gc.fit_rho_to_size({k: rho[k] for k in tr}, {k: opt[k] for k in tr})\n"
    "pred_rho = {k: gc.predict_size(rho[k], fit_rho, l_min=50, l_max=400) for k in te}\n"
    "\n"
    "# (ii) select the strongest single density feature on TRAIN, then fit size = a + b*feature.\n"
    "sel = gc.select_and_fit(feats, opt, tr, feature_names=FEATURE_NAMES)\n"
    "print(f\"selected feature: {sel['feature']}  (train corr {sel['corr']:+.3f})\")\n"
    "print('rho fit     :', fit_rho)\n"
    "print('feature fit :', sel['fit'])\n"
    "pred_feat = {k: gc.predict_size(feats[k][sel['feature']], sel['fit'], 50, 400) for k in te}\n"
    "\n"
    "# Score each policy on the TEST docs (coverage snapped to the swept grid).\n"
    "best_fixed_size, _ = gc.best_global_fixed(records)\n"
    "cov_fixed    = gc.coverage_under_sizes(records, {k: best_fixed_size for k in te})\n"
    "cov_rho      = gc.coverage_under_sizes(records, pred_rho)\n"
    "cov_density  = gc.coverage_under_sizes(records, pred_feat)   # headline training-free arm\n"
    "_, oracle_sizes = gc.oracle_per_doc(records)\n"
    "cov_oracle   = gc.coverage_under_sizes(records, {k: oracle_sizes[k] for k in te if k in oracle_sizes})\n"
    "\n"
    "print()\n"
    "print(f\"{'policy (TEST docs)':<38}{'mean coverage':>14}\")\n"
    "print('-' * 52)\n"
    "print(f\"{'best global fixed (' + str(best_fixed_size) + ' tok)':<38}{cov_fixed:>14.4f}\")\n"
    "print(f\"{'training-free: composite rho->size':<38}{cov_rho:>14.4f}\")\n"
    "print(f\"{'training-free: ' + str(sel['feature']) + '->size':<38}{cov_density:>14.4f}\")\n"
    "print(f\"{'per-doc oracle (ceiling)':<38}{cov_oracle:>14.4f}\")"
))

# 9. code -- LEARNED baseline (sklearn)
cells.append(new_code_cell(
    "# Learned baseline: a 6-feature linear regressor (sklearn) fit on TRAIN, evaluated\n"
    "# on TEST the same way. Shows whether the training-free 2-param map is competitive\n"
    "# with a fully learned multi-feature model.\n"
    "from sklearn.linear_model import LinearRegression\n"
    "\n"
    "X_tr = [[feats[k][f] for f in FEATURE_NAMES] for k in tr]\n"
    "y_tr = [opt[k] for k in tr]\n"
    "reg = LinearRegression().fit(X_tr, y_tr)\n"
    "\n"
    "def _clip_size(v, lo=50, hi=400):\n"
    "    return int(max(lo, min(hi, round(v))))\n"
    "\n"
    "pred_test_learned = {\n"
    "    k: _clip_size(reg.predict([[feats[k][f] for f in FEATURE_NAMES]])[0]) for k in te\n"
    "}\n"
    "cov_learned = gc.coverage_under_sizes(records, pred_test_learned)\n"
    "\n"
    "print(f\"{'policy (TEST docs)':<40}{'mean coverage':>14}\")\n"
    "print('-' * 54)\n"
    "print(f\"{'best global fixed':<40}{cov_fixed:>14.4f}\")\n"
    "print(f\"{'training-free: composite rho':<40}{cov_rho:>14.4f}\")\n"
    "print(f\"{'training-free: selected feature (1 param)':<40}{cov_density:>14.4f}\")\n"
    "print(f\"{'learned regressor (sklearn, 6 feat)':<40}{cov_learned:>14.4f}\")\n"
    "print(f\"{'per-doc oracle (ceiling)':<40}{cov_oracle:>14.4f}\")"
))

# 9b. code -- ROBUSTNESS over many random splits (the H2 statistic to quote)
cells.append(new_code_cell(
    "# Robustness of Table 1: repeat the held-out evaluation over many random train/test\n"
    "# splits. A single 70/30 split on ~50 docs leaves a ~15-doc test set (high variance),\n"
    "# so the honest H2 statistic is the DISTRIBUTION of test coverage across splits plus\n"
    "# how often the training-free selected-feature map actually beats the best fixed size.\n"
    "# Free: runs on the already-cached sweep records. best-global-fixed is chosen over ALL\n"
    "# docs (a deliberately STRONG, mildly optimistic baseline -> a conservative H2 test).\n"
    "import statistics\n"
    "\n"
    "N_SPLITS = 50\n"
    "_rows = {'best global fixed': [], 'training-free: composite rho': [],\n"
    "         'training-free: selected feature': [], 'learned (6 feat)': [], 'per-doc oracle': []}\n"
    "_wins_feat = 0\n"
    "_sel_freq = Counter()\n"
    "bf_size, _ = gc.best_global_fixed(records)\n"
    "_, oracle_sizes_all = gc.oracle_per_doc(records)\n"
    "\n"
    "for _seed in range(N_SPLITS):\n"
    "    _tr, _te = gc.train_test_split_docs(list(opt), seed=_seed)\n"
    "    if not _tr or not _te:\n"
    "        continue\n"
    "    # training-free: composite rho\n"
    "    _fr = gc.fit_rho_to_size({k: rho[k] for k in _tr}, {k: opt[k] for k in _tr})\n"
    "    _pr = {k: gc.predict_size(rho[k], _fr, 50, 400) for k in _te}\n"
    "    # training-free: strongest single feature, selected on THIS split's train only\n"
    "    _se = gc.select_and_fit(feats, opt, _tr, feature_names=FEATURE_NAMES)\n"
    "    _sel_freq[_se['feature']] += 1\n"
    "    _pf = ({k: gc.predict_size(feats[k][_se['feature']], _se['fit'], 50, 400) for k in _te}\n"
    "           if _se['feature'] else {})\n"
    "    # learned 6-feature regressor (same recipe as the cell above)\n"
    "    _reg = LinearRegression().fit([[feats[k][f] for f in FEATURE_NAMES] for k in _tr],\n"
    "                                  [opt[k] for k in _tr])\n"
    "    _pl = {k: _clip_size(_reg.predict([[feats[k][f] for f in FEATURE_NAMES]])[0]) for k in _te}\n"
    "    # score every policy on THIS split's TEST docs (snapped to the swept grid)\n"
    "    _cf = gc.coverage_under_sizes(records, {k: bf_size for k in _te})\n"
    "    _cr = gc.coverage_under_sizes(records, _pr)\n"
    "    _cd = gc.coverage_under_sizes(records, _pf) if _pf else float('nan')\n"
    "    _cl = gc.coverage_under_sizes(records, _pl)\n"
    "    _co = gc.coverage_under_sizes(records,\n"
    "                                  {k: oracle_sizes_all[k] for k in _te if k in oracle_sizes_all})\n"
    "    _rows['best global fixed'].append(_cf)\n"
    "    _rows['training-free: composite rho'].append(_cr)\n"
    "    _rows['training-free: selected feature'].append(_cd)\n"
    "    _rows['learned (6 feat)'].append(_cl)\n"
    "    _rows['per-doc oracle'].append(_co)\n"
    "    if _cd == _cd and _cd > _cf:   # _cd == _cd skips NaN splits\n"
    "        _wins_feat += 1\n"
    "\n"
    "def _mean_std(xs):\n"
    "    xs = [x for x in xs if x == x]\n"
    "    return (statistics.mean(xs), statistics.pstdev(xs)) if xs else (float('nan'), 0.0)\n"
    "\n"
    "print(f'H2 robustness over {N_SPLITS} random 70/30 splits (mean +/- std TEST coverage)')\n"
    "print(f\"{'policy':<36}{'mean':>9}{'std':>9}\")\n"
    "print('-' * 54)\n"
    "for _k in ['best global fixed', 'training-free: composite rho',\n"
    "           'training-free: selected feature', 'learned (6 feat)', 'per-doc oracle']:\n"
    "    _m, _sd = _mean_std(_rows[_k])\n"
    "    print(f'{_k:<36}{_m:>9.4f}{_sd:>9.4f}')\n"
    "print()\n"
    "print(f'selected-feature map beats best-global-fixed in {_wins_feat}/{N_SPLITS} splits')\n"
    "print('selected-feature frequency across splits:', dict(_sel_freq))"
))

# 10. md -- reading guide
cells.append(new_markdown_cell(
    "## How to read this\n"
    "\n"
    "- **Headroom (Fig.1).** If the per-doc oracle sits well above the best fixed-size "
    "point, there is real coverage to be won by sizing leaves per document. A negligible "
    "`abs_gap` means a fixed size is already near-optimal and the adaptive story is weak.\n"
    "- **Correlation (the key diagnostic).** The signal(s) with the largest-magnitude "
    "Spearman vs optimal size carry granularity information; near-zero rows are dead "
    "features. **The 8-doc pilot found the equal-weight composite `rho` is near-zero "
    "(+0.04) while individual features are strong but OPPOSITELY signed** "
    "(`mean_word_len` +0.79, `nonstopword_ratio` +0.66, `type_token_ratio` −0.60) — so "
    "averaging them cancels the signal. The composite's `invert=True` 'denser⇒smaller' "
    "assumption is also only half-right: two 'harder-text' features want *larger* leaves. "
    "That is why the headline training-free arm **selects the strongest single feature on "
    "TRAIN** rather than trusting the hand-weighted composite.\n"
    "- **Adaptive wins** when, on the **held-out TEST** docs, the **selected-feature** "
    "coverage **exceeds best global fixed** and **approaches the per-doc oracle** "
    "(the composite-`rho` row is kept only to show the cancellation).\n"
    "- **Training-free ≈ learned** when the parsimonious 1-parameter selected-feature map "
    "lands close to the 6-feature sklearn regressor on TEST. If so, the cheap, "
    "interpretable, label-free map is the one to ship — no per-corpus training at "
    "inference.\n"
    "- **Robustness (the H2 number to quote).** The single 70/30 split above is "
    "illustrative; the repeated-split cell is the headline. Report **mean ± std TEST "
    "coverage over 50 random splits** and the **win-rate** of the selected-feature map "
    "over best-global-fixed. A clear H2 pass = a high win-rate **and** a *stable* selected "
    "feature (one feature chosen in most splits). A near-50% win-rate, large std, or a "
    "feature that flips across splits means the signal is too weak at this N — scale "
    "`limit=` before claiming H2.\n"
    "- **N caveat.** Selecting one of six features on a small sample is mildly optimistic; "
    "the held-out TEST split guards against it, but treat single-feature wins at small "
    "`limit=` as directional. Scale `limit=` (the sweep caches + resumes) before quoting "
    "the correlation or the ship/no-ship call.\n"
    "\n"
    "Scale up `limit=` if the picture is borderline; the sweep is cached in `OUT` and "
    "resumes, so re-running only embeds the newly added documents."
))

nb = new_notebook(cells=cells)
nb.metadata["colab"] = {"provenance": []}
nb.metadata["kernelspec"] = {
    "display_name": "Python 3", "language": "python", "name": "python3",
}
nb.metadata["language_info"] = {"name": "python"}
nb.nbformat = 4
nb.nbformat_minor = 5

out = "notebooks/granularity_calibration.ipynb"
with open(out, "w") as f:
    nbf.write(nb, f)
print("wrote", out, "with", len(nb.cells), "cells")
